"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y(3e@$0m_00tfsugagc63zho@6(#clym%vfdxau0g#n6^xbva('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_components',
    'django_adminlte4',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'spi',  # App Solicitação de Pedidos Interno
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'django_components.template_loader.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_adminlte4.context_processors.adminlte',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('NAME_DB'),
        'HOST': config('HOST_DB'),
        'USER': config('USER_DB'),
        'PASSWORD': config('PASSWORD_DB'),
        'PORT': config('PORT_DB'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# valores monetários brasileiro
USE_THOUSAND_SEPARATOR = True

DECIMAL_SEPARATOR = ","

THOUSAND_SEPARATOR = "."


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

COMPONENTS = {
    'dirs': [],
    'app_dirs': ['components'],
    'autodiscover': True,
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


def is_administrator(request):
    return request.user.is_authenticated and request.user.is_staff


ADMINLTE = {
    'title': 'SPI',
    'title_postfix': ' | Sistema de Pedidos Internos',
    'logo': '<b>SPI</b>',
    'logo_alt_text': 'SPI',
    'logo_img': 'images/spi-mark.svg',
    'logo_img_alt': 'SPI',
    'logo_img_class': 'brand-image',
    'admin_brand': 'Administração SPI',
    'admin_enabled': True,
    'assets_mode': 'static',
    'sidebar_theme': 'light',
    'classes_sidebar': 'bg-white shadow-sm',
    'classes_topnav': 'navbar-expand bg-white border-bottom',
    'classes_content': 'dashboard-content',
    'navbar_search': False,
    'color_mode_toggle': False,
    'sidebar_docs_url': False,
    'footer_left': 'SPI &copy; 2026',
    'footer_right': 'Sistema de Pedidos Internos',
    # Itens exibidos no menu lateral do dashboard.
    'menu': [
        {'text': 'Início', 'icon': 'bi bi-house-door-fill', 'route': 'dashboard'},
        {
            'text': 'Administrar',
            'icon': 'bi bi-briefcase-fill',
            'can': is_administrator,
            'submenu': [
                {'text': 'Usuários', 'icon': 'bi bi-people', 'route': 'user_list', 'can': 'auth.view_user'},
                {'text': 'Grupos', 'icon': 'bi bi-collection', 'route': 'group_list', 'can': 'auth.view_group'},
                {'text': 'Produtos', 'icon': 'bi bi-box-seam', 'route': 'product_list', 'can': 'spi.view_produto'},
                {'text': 'Descartes', 'icon': 'bi bi-trash', 'route': 'discard_list', 'can': 'spi.view_descarte'},
                {'text': 'Inventário', 'icon': 'bi bi-clipboard2-data-fill', 'route': 'inventory_list', 'can': 'spi.view_inventario'},
            ],
        },
    ],
}
