# Generated by Django 6.0.7 on 2026-07-31 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da atualização')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do cadastro')),
            ],
            options={
                'verbose_name': 'Controle de data',
                'verbose_name_plural': 'Controles de data',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('cnpj_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('cep_fornecedor', models.CharField(max_length=9, verbose_name='CEP')),
                ('telefone_fornecedor', models.CharField(max_length=32, verbose_name='Telefone')),
                ('whatsapp_fornecedor', models.CharField(max_length=32, verbose_name='whatsapp')),
                ('responsavel_fornecedor', models.CharField(max_length=255, verbose_name='Responsável')),
                ('controle_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='spi.controledata', verbose_name='Controle de datas')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_fornecedor'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=30, unique=True, verbose_name='Nº Patrimônio')),
                ('id_ativo', models.CharField(max_length=30, unique=True, verbose_name='ID do Inventario')),
                ('categoria', models.CharField(choices=[('NOTE', 'Notebook'), ('DESK', 'Desktop'), ('MONI', 'Monitor'), ('IMP', 'Impressora'), ('NOBR', 'Nobreak'), ('SERV', 'Servidor'), ('OUTR', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('item_modelo', models.CharField(max_length=150, verbose_name='Item / Modelo')),
                ('serie_licenca', models.CharField(blank=True, max_length=150, null=True, verbose_name='S/N (Série) / Licença')),
                ('data_aquisicao', models.DateField(verbose_name='Data Aquisição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('validade_garantia', models.DateField(blank=True, null=True, verbose_name='Validade / Garantia')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUT', 'Em Manutenção'), ('DESC', 'Descartado')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'inventarios',
                'ordering': ['numero_patrimonio'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('controle_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='spi.controledata', verbose_name='Controle de datas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='spi.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_barras', models.CharField(max_length=128, unique=True, verbose_name='Código de barras')),
                ('controle_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='spi.controledata', verbose_name='Controle de datas')),
                ('responsavel_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo cadastro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo do descarte')),
                ('destinacao', models.CharField(choices=[('REC', 'Reciclagem'), ('REA', 'Reaproveitamento'), ('DOA', 'Doação'), ('LIX', 'Lixo Comum'), ('RES', 'Resíduo Perigoso')], default='LIX', max_length=3, verbose_name='Destinação recomendada')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_descarte', models.DateTimeField(auto_now_add=True, verbose_name='Data do descarte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descartes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descartes', to='spi.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descartes',
                'ordering': ['-data_descarte'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantidade_produto', models.PositiveIntegerField(verbose_name='Quantidade do produto')),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, verbose_name='Valor do produto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, verbose_name='Total')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('COMPRADO', 'Comprado'), ('RECEBIDO', 'Recebido')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('controle_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_pedidos', to='spi.controledata', verbose_name='Controle de datas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='spi.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto do pedido',
                'verbose_name_plural': 'Produtos dos pedidos',
                'ordering': ['-controle_data__data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ValorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('controle_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_produtos', to='spi.controledata', verbose_name='Controle de datas')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_produtos', to='spi.link', verbose_name='Link')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='spi.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Valor de produto',
                'verbose_name_plural': 'Valores de produtos',
                'ordering': ['-controle_data__data_cadastro'],
            },
        ),
    ]
