# Generated by Django 6.0.7 on 2026-07-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('link_produto', models.URLField(max_length=2048)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_produto', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('data_descarte', models.DateField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descartes', to='spi.produto')),
            ],
        ),
    ]
