# Generated by Django 6.0.7 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('link_produto', models.URLField(max_length=2048)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
