# Generated by Django 6.0.7 on 2026-08-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='spi.link', verbose_name='Link do produto'),
        ),
    ]
