# Generated by Django 6.0.7 on 2026-07-31 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0002_inventatio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descarte',
            options={'ordering': ['-data_descarte'], 'verbose_name': 'Descarte', 'verbose_name_plural': 'Descartes'},
        ),
        migrations.AddField(
            model_name='descarte',
            name='destinacao',
            field=models.CharField(choices=[('REC', 'Reciclagem'), ('REA', 'Reaproveitamento'), ('DOA', 'Doação'), ('LIX', 'Lixo Comum'), ('RES', 'Resíduo Perigoso')], default='LIX', max_length=3, verbose_name='Destinação recomendada'),
        ),
        migrations.AddField(
            model_name='descarte',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='descartes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descarte',
            name='data_descarte',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do descarte'),
        ),
        migrations.AlterField(
            model_name='descarte',
            name='motivo',
            field=models.CharField(max_length=255, verbose_name='Motivo do descarte'),
        ),
        migrations.AlterField(
            model_name='descarte',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='descarte',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descartes', to='spi.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='descarte',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
