# Generated by Django 6.0.7 on 2026-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0002_produtopedido_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade do produto', verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='valorproduto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitário'),
        ),
    ]
