# Generated by Django 6.0.7 on 2026-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0003_valorproduto_quantidade_alter_valorproduto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorproduto',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='valorproduto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
    ]
