# Generated by Django 6.0.7 on 2026-07-31 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_produtos_existentes(apps, schema_editor):
    Produto = apps.get_model("spi", "Produto")
    ControleData = apps.get_model("spi", "ControleData")
    Fornecedor = apps.get_model("spi", "Fornecedor")
    Link = apps.get_model("spi", "Link")
    ValorProduto = apps.get_model("spi", "ValorProduto")
    ProdutoPedido = apps.get_model("spi", "ProdutoPedido")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    produtos = list(Produto.objects.all())
    if not produtos:
        return

    usuario = User.objects.order_by("pk").first()
    if usuario is None:
        raise RuntimeError(
            "Não é possível migrar produtos existentes sem um usuário responsável."
        )

    for produto in produtos:
        controle_produto = ControleData.objects.create(
            usuario_cadastro=usuario,
            usuario_atualizacao=usuario,
        )
        produto.nome = produto.nome_produto
        produto.codigo_barras = f"LEGACY-{produto.pk}"
        produto.responsavel_cadastro = usuario
        produto.controle_data = controle_produto
        produto.save(
            update_fields=(
                "nome",
                "codigo_barras",
                "responsavel_cadastro",
                "controle_data",
            )
        )

        controle_fornecedor = ControleData.objects.create(
            usuario_cadastro=usuario,
            usuario_atualizacao=usuario,
        )
        fornecedor = Fornecedor.objects.create(
            nome_fornecedor=f"Fornecedor legado - {produto.nome_produto}"[:255],
            cnpj_cnpj=f"LEGACY-{produto.pk}",
            telefone_fornecedor="Não informado",
            responsavel_forncedor="Não informado",
            controle_data=controle_fornecedor,
        )

        controle_link = ControleData.objects.create(
            usuario_cadastro=usuario,
            usuario_atualizacao=usuario,
        )
        link = Link.objects.create(
            nome=f"Link legado - {produto.nome_produto}"[:255],
            url=produto.link_produto,
            fornecedor=fornecedor,
            controle_data=controle_link,
        )

        controle_valor = ControleData.objects.create(
            usuario_cadastro=usuario,
            usuario_atualizacao=usuario,
        )
        ValorProduto.objects.create(
            produto=produto,
            link=link,
            valor=produto.preco_atual,
            controle_data=controle_valor,
        )

        if produto.quantidade_produto:
            controle_pedido = ControleData.objects.create(
                usuario_cadastro=usuario,
                usuario_atualizacao=usuario,
            )
            ProdutoPedido.objects.create(
                nome=produto.nome_produto,
                descricao="Registro convertido do cadastro anterior de produtos.",
                produto=produto,
                quantidade_produto=produto.quantidade_produto,
                controle_data=controle_pedido,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0003_alter_descarte_options_descarte_destinacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_cadastro", models.DateTimeField(auto_now_add=True, verbose_name="Data de cadastro")),
                ("data_atualizacao", models.DateTimeField(auto_now=True, verbose_name="Data de atualização")),
                ("usuario_atualizacao", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controles_atualizados", to=settings.AUTH_USER_MODEL, verbose_name="Usuário da atualização")),
                ("usuario_cadastro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controles_criados", to=settings.AUTH_USER_MODEL, verbose_name="Usuário do cadastro")),
            ],
            options={
                "verbose_name": "Controle de data",
                "verbose_name_plural": "Controles de data",
                "ordering": ["-data_atualizacao"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_fornecedor", models.CharField(max_length=255, verbose_name="Nome do fornecedor")),
                ("cnpj_cnpj", models.CharField(max_length=18, unique=True, verbose_name="CNPJ")),
                ("telefone_fornecedor", models.CharField(max_length=32, verbose_name="Telefone")),
                ("responsavel_forncedor", models.CharField(max_length=255, verbose_name="Responsável")),
                ("controle_data", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fornecedores", to="spi.controledata", verbose_name="Controle de datas")),
            ],
            options={"verbose_name": "Fornecedor", "verbose_name_plural": "Fornecedores", "ordering": ["nome_fornecedor"]},
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("url", models.URLField(max_length=2048, verbose_name="URL")),
                ("controle_data", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="links", to="spi.controledata", verbose_name="Controle de datas")),
                ("fornecedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="links", to="spi.fornecedor", verbose_name="Fornecedor")),
            ],
            options={"verbose_name": "Link", "verbose_name_plural": "Links", "ordering": ["nome"]},
        ),
        migrations.AddField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255, null=True, verbose_name="Nome"),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_barras",
            field=models.CharField(max_length=128, null=True, verbose_name="Código de barras"),
        ),
        migrations.AddField(
            model_name="produto",
            name="controle_data",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="produtos", to="spi.controledata", verbose_name="Controle de datas"),
        ),
        migrations.AddField(
            model_name="produto",
            name="responsavel_cadastro",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="produtos_cadastrados", to=settings.AUTH_USER_MODEL, verbose_name="Responsável pelo cadastro"),
        ),
        migrations.CreateModel(
            name="ProdutoPedido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("quantidade_produto", models.PositiveIntegerField(verbose_name="Quantidade do produto")),
                ("controle_data", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="produtos_pedidos", to="spi.controledata", verbose_name="Controle de datas")),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pedidos", to="spi.produto", verbose_name="Produto")),
            ],
            options={"verbose_name": "Produto do pedido", "verbose_name_plural": "Produtos dos pedidos", "ordering": ["-controle_data__data_cadastro"]},
        ),
        migrations.CreateModel(
            name="ValorProduto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Valor")),
                ("controle_data", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="valores_produtos", to="spi.controledata", verbose_name="Controle de datas")),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="valores_produtos", to="spi.link", verbose_name="Link")),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="valores", to="spi.produto", verbose_name="Produto")),
            ],
            options={"verbose_name": "Valor de produto", "verbose_name_plural": "Valores de produtos", "ordering": ["-controle_data__data_cadastro"]},
        ),
        migrations.RunPython(migrar_produtos_existentes, migrations.RunPython.noop),
        migrations.RemoveField(model_name="produto", name="link_produto"),
        migrations.RemoveField(model_name="produto", name="nome_produto"),
        migrations.RemoveField(model_name="produto", name="preco_atual"),
        migrations.RemoveField(model_name="produto", name="quantidade_produto"),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo_barras",
            field=models.CharField(max_length=128, unique=True, verbose_name="Código de barras"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="controle_data",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="produtos", to="spi.controledata", verbose_name="Controle de datas"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="responsavel_cadastro",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="produtos_cadastrados", to=settings.AUTH_USER_MODEL, verbose_name="Responsável pelo cadastro"),
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ["nome"], "verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
    ]
