# Generated by Django 6.0.7 on 2026-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0004_refatora_catalogo_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('COMPRADO', 'Comprado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
    ]
