# Generated by Django 6.0.7 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0004_remove_valorproduto_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
