# Generated by Django 6.0.7 on 2026-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0005_fornecedor_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='cep_fornecedor',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='whatsapp_fornecedor',
            field=models.CharField(max_length=32, verbose_name='WhatsApp'),
        ),
    ]
