# Generated by Django 6.0.7 on 2026-08-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0006_remove_fornecedor_cep_fornecedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='cep',
            new_name='cep_fornecedor',
        ),
    ]
