# Generated by Django 6.0.7 on 2026-08-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0008_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email_fornecedor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
