# Generated by Django 6.0.7 on 2026-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0009_fornecedor_email_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=2),
        ),
    ]
