# Generated by Django 6.0.7 on 2026-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0010_produto_estoque_atual_produto_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='produtopedido',
            name='valor_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
