# Generated by Django 6.0.7 on 2026-09-01 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0011_produtopedido_total_produtopedido_valor_produto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade Disponível')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('valor_unitario_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário Atual')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('responsavel_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo cadastro')),
            ],
            options={
                'verbose_name': 'Produto em estoque',
                'verbose_name_plural': 'Produtos em estoque',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentoBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('finalizado', models.BooleanField(default=False)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento em Lote',
                'verbose_name_plural': 'Movimentos em Lote',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], db_index=True, max_length=1, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='spi.estoque', verbose_name='Item do Estoque')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['nome'], name='spi_estoque_nome_5fecdf_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['quantidade_estoque', 'estoque_minimo'], name='spi_estoque_quantid_e2b2be_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['estoque', '-data_movimentacao'], name='spi_movimen_estoque_f5054b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', 'data_movimentacao'], name='spi_movimen_tipo_4069b4_idx'),
        ),
    ]
