# Generated by Django 6.0.7 on 2026-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0012_estoque_estoquemovimentobatch_movimentacaoestoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='valor_unitario_atual',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário Atual'),
        ),
    ]
