# Generated by Django 6.0.7 on 2026-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0013_alter_estoque_valor_unitario_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_ativo',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('SRV', 'Servidor'), ('NET', 'Rede'), ('PER', 'Periféricos'), ('CLD', 'Serviços em nuvem'), ('SEC', 'Segurança'), ('LIC', 'Licenças')], max_length=30, unique=True, verbose_name='ID do Inventario'),
        ),
    ]
