# Generated by Django 6.0.7 on 2026-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0014_alter_inventario_id_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total (R$)'),
        ),
    ]
