# Generated by Django 6.0.7 on 2026-09-08 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0015_inventario_quantidade_inventario_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['numero_patrimonio'], 'verbose_name': 'Inventário', 'verbose_name_plural': 'Inventários'},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_ativo',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('SRV', 'Servidor'), ('NET', 'Rede'), ('PER', 'Periféricos'), ('CLD', 'Serviços em nuvem'), ('SEC', 'Segurança'), ('LIC', 'Licenças')], max_length=30, verbose_name='ID do Inventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
