# Generated by Django 6.0.7 on 2026-09-09 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0016_alter_inventario_options_alter_inventario_id_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquemovimentobatch',
            name='responsavel',
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='estoque',
            name='spi_estoque_nome_5fecdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='estoque',
            name='spi_estoque_quantid_e2b2be_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='spi_movimen_estoque_f5054b_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='spi_movimen_tipo_4069b4_idx',
        ),
        migrations.AddField(
            model_name='inventario',
            name='estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='spi.estoque', verbose_name='Produto do Estoque'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUT', 'Em Manutenção'), ('DESC', 'Descartado')], default='ATIVO', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='validade_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Garantia'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo de Movimentação'),
        ),
        migrations.DeleteModel(
            name='EstoqueMovimentoBatch',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='responsavel_cadastro',
        ),
    ]
