# Generated by Django 6.0.7 on 2026-09-10 03:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0017_remove_estoquemovimentobatch_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueMovimentoBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('finalizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Movimento em Lote',
                'verbose_name_plural': 'Movimentos em Lote',
            },
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Produto em estoque', 'verbose_name_plural': 'Produtos em estoque'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data_movimentacao'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='estoque',
        ),
        migrations.AddField(
            model_name='estoque',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
    model_name='estoque',
    name='responsavel_cadastro',
    field=models.ForeignKey(
        null=True,
        blank=True,
        on_delete=django.db.models.deletion.SET_NULL,
        to='auth.user',
    ),
),
        migrations.AlterField(
            model_name='inventario',
            name='setor',
            field=models.CharField(max_length=100, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUT', 'Em Manutenção'), ('DESC', 'Descartado')], default='ATIVO', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='validade_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Validade / Garantia'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], db_index=True, max_length=1, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['nome'], name='spi_estoque_nome_5fecdf_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['quantidade_estoque', 'estoque_minimo'], name='spi_estoque_quantid_e2b2be_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['estoque', '-data_movimentacao'], name='spi_movimen_estoque_f5054b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', 'data_movimentacao'], name='spi_movimen_tipo_4069b4_idx'),
        ),
        migrations.AddField(
            model_name='estoquemovimentobatch',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
