# Generated by Django 6.0.7 on 2026-09-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0018_estoquemovimentobatch_alter_estoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='responsavel_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoque_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo cadastro'),
        ),
    ]
