# Generated by Django 6.0.7 on 2026-09-28 03:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0019_alter_estoque_responsavel_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquemovimentobatch',
            name='responsavel',
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['produto'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.RemoveIndex(
            model_name='estoque',
            name='spi_estoque_nome_5fecdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='estoque',
            name='spi_estoque_quantid_e2b2be_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='spi_movimen_estoque_f5054b_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='spi_movimen_tipo_4069b4_idx',
        ),
        migrations.AddField(
            model_name='estoque',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='entrada',
            field=models.PositiveIntegerField(default=0, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.CharField(default='Sem produto', max_length=150, verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='spi.estoque'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10),
        ),
        migrations.DeleteModel(
            name='EstoqueMovimentoBatch',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade_estoque',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='responsavel_cadastro',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='valor_unitario_atual',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='total',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='valor_unitario',
        ),
    ]
