# Generated by Django 6.0.7 on 2026-10-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0020_remove_estoquemovimentobatch_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.AddField(
            model_name='estoque',
            name='localizacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Localização'),
        ),
    ]
