# Generated by Django 6.0.7 on 2026-10-02 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0021_alter_movimentacaoestoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='localizacao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Localização'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='spi.estoque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
