# Generated by Django 6.0.7 on 2026-10-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0022_alter_estoque_localizacao_entrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='ordem_fornecimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ordem de Fornecimento'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº NF'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo (Unidade)'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='spi.estoque', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade Recebida'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
