# Generated by Django 6.0.7 on 2026-10-02 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0023_entrada_ordem_fornecimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='ordem_fornecimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº OF'),
        ),
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade_saida', models.PositiveIntegerField(verbose_name='Quantidade Saída')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('motivo_destino', models.CharField(choices=[('USO_INTERNO', 'Uso Interno'), ('VENDA', 'Venda'), ('DESCARTE', 'Descarte / Avaria'), ('TRANSFERENCIA', 'Transferência'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Motivo / Destino')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Saída de Produto',
                'verbose_name_plural': 'Saídas de Produtos',
                'ordering': ['-data_hora'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
