# Generated by Django 6.0.7 on 2026-10-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0025_entrada_produto_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='produto_catalogo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saldo_estoque', to='spi.produto', verbose_name='Produto do catálogo'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='entrada_origem',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_automatica', to='spi.entrada'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='saida_origem',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_automatica', to='spi.saidaproduto'),
        ),
    ]
