# Generated by Django 6.0.7 on 2026-10-06 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0026_estoque_produto_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='spi.estoque'),
        ),
    ]
