"""Ponto de entrada das views funcionais da área de gestão."""

from .access import (
    create_group,
    create_user,
    delete_group,
    delete_user,
    list_groups,
    list_users,
    update_group,
    update_user,
)
from .inventory import (
    create_discard,
    create_inventory,
    delete_discard,
    list_discards,
    list_inventory,
    update_discard,
)
from .products import (
    create_order_product,
    create_product,
    create_product_from_modal,
    create_product_value,
    delete_order_product,
    delete_product,
    delete_product_value,
    list_order_products,
    list_product_values,
    list_products,
    update_order_product,
    update_product,
    update_product_value,
)
from .suppliers import (
    create_link,
    create_supplier,
    create_supplier_from_product,
    delete_link,
    delete_supplier,
    list_links,
    list_suppliers,
    update_link,
    update_supplier,
)


__all__ = [
    "create_discard",
    "create_group",
    "create_inventory",
    "create_link",
    "create_order_product",
    "create_product",
    "create_product_from_modal",
    "create_product_value",
    "create_supplier",
    "create_supplier_from_product",
    "create_user",
    "delete_discard",
    "delete_group",
    "delete_link",
    "delete_order_product",
    "delete_product",
    "delete_product_value",
    "delete_supplier",
    "delete_user",
    "list_discards",
    "list_groups",
    "list_inventory",
    "list_links",
    "list_order_products",
    "list_product_values",
    "list_products",
    "list_suppliers",
    "list_users",
    "update_discard",
    "update_group",
    "update_link",
    "update_order_product",
    "update_product",
    "update_product_value",
    "update_supplier",
    "update_user",
]
